#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Enable copr repositories.
sudo dnf copr enable -y thelocehiliosan/yadm
sudo dnf copr enable -y carlwgeorge/ripgrep

# Enable yarn repository.
sudo wget 'https://dl.yarnpkg.com/rpm/yarn.repo' -O /etc/yum.repos.d/yarn.repo

# Install required packages.
sudo dnf install -y openssl-devel cmake python3-devel

# Install software.
sudo dnf install -y yadm tmux vim-enhanced zsh terminator i3 fzf ripgrep yarn redshift

# Clone and install asdf.
git clone 'https://github.com/asdf-vm/asdf.git' "${HOME}/.asdf" --branch v0.4.1

# Install nodejs.
asdf plugin-add nodejs
${HOME}/.asdf/plugins/nodejs/bin/import-release-team-keyring
asdf install nodejs 9.3.0
asdf global nodejs 9.3.0

# Clone dotfiles.
yadm clone 'https://github.com/tstelzer/dotfiles' --no-bootstrap

# Change default login shell.
sudo usermod -s /bin/zsh ${USER}

# Install rust toolchain.
curl 'https://sh.rustup.rs' -sSf | sh -s -- --default-toolchain stable -y

# Add cargo to path.
if [ -d "${HOME}/.cargo/bin" ]; then
    export PATH="$PATH:${HOME}/.cargo/bin"
fi

# Install cargo software.
cargo install cargo-update fd-find --quiet

# Install i3pystatus dependencies.
pip3 install -q --user 'git+https://github.com/enkore/i3pystatus.git' colour netifaces

# Get iosevka font.
# wget -O "${HOME}/tmp/iosevka.zip" 'https://github.com/be5invis/Iosevka/releases/download/v1.13.3/iosevka-term-ss09-1.13.3.zip'

# mkdir "${HOME}/.fonts"\ 
#     && cd "${HOME}/tmp"\ 
#     && unzip "iosevka-term-ss09-1.13.3.zip"\ 
#     && mv ttf/* "${HOME}/.fonts/"\ 
#     && fs-cache -fs

# sudo echo "Run 'vim -c PlugInstall -c q -q!'" > /etc/motd
